// Code generated by go-swagger; DO NOT EDIT.

package tendermint_rpc

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetBlocksLatestParams creates a new GetBlocksLatestParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetBlocksLatestParams() *GetBlocksLatestParams {
	return &GetBlocksLatestParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetBlocksLatestParamsWithTimeout creates a new GetBlocksLatestParams object
// with the ability to set a timeout on a request.
func NewGetBlocksLatestParamsWithTimeout(timeout time.Duration) *GetBlocksLatestParams {
	return &GetBlocksLatestParams{
		timeout: timeout,
	}
}

// NewGetBlocksLatestParamsWithContext creates a new GetBlocksLatestParams object
// with the ability to set a context for a request.
func NewGetBlocksLatestParamsWithContext(ctx context.Context) *GetBlocksLatestParams {
	return &GetBlocksLatestParams{
		Context: ctx,
	}
}

// NewGetBlocksLatestParamsWithHTTPClient creates a new GetBlocksLatestParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetBlocksLatestParamsWithHTTPClient(client *http.Client) *GetBlocksLatestParams {
	return &GetBlocksLatestParams{
		HTTPClient: client,
	}
}

/* GetBlocksLatestParams contains all the parameters to send to the API endpoint
   for the get blocks latest operation.

   Typically these are written to a http.Request.
*/
type GetBlocksLatestParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get blocks latest params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetBlocksLatestParams) WithDefaults() *GetBlocksLatestParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get blocks latest params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetBlocksLatestParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get blocks latest params
func (o *GetBlocksLatestParams) WithTimeout(timeout time.Duration) *GetBlocksLatestParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get blocks latest params
func (o *GetBlocksLatestParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get blocks latest params
func (o *GetBlocksLatestParams) WithContext(ctx context.Context) *GetBlocksLatestParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get blocks latest params
func (o *GetBlocksLatestParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get blocks latest params
func (o *GetBlocksLatestParams) WithHTTPClient(client *http.Client) *GetBlocksLatestParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get blocks latest params
func (o *GetBlocksLatestParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetBlocksLatestParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
