// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
)

// Hash hash
// Example: EE5F3404034C524501629B56E0DDC38FAD651F04
//
// swagger:model Hash
type Hash string

// Validate validates this hash
func (m Hash) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this hash based on context it is used
func (m Hash) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}
