// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
)

// Msg msg
//
// swagger:model Msg
type Msg string

// Validate validates this msg
func (m Msg) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this msg based on context it is used
func (m Msg) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}
