// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// OracleParams oracle params
//
// swagger:model OracleParams
type OracleParams struct {

	// drop threshold
	// Example: 10
	DropThreshold string `json:"drop_threshold,omitempty"`

	// oracle reward band
	// Example: 0.02
	OracleRewardBand string `json:"oracle_reward_band,omitempty"`

	// slash window
	// Example: 43200
	SlashWindow string `json:"slash_window,omitempty"`

	// vote period
	// Example: 900
	VotePeriod string `json:"vote_period,omitempty"`

	// vote threshold
	// Example: 0.67
	VoteThreshold string `json:"vote_threshold,omitempty"`
}

// Validate validates this oracle params
func (m *OracleParams) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this oracle params based on context it is used
func (m *OracleParams) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *OracleParams) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *OracleParams) UnmarshalBinary(b []byte) error {
	var res OracleParams
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
