// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// ValidatorInfo validator info
//
// swagger:model ValidatorInfo
type ValidatorInfo struct {

	// commission
	// Required: true
	Commission *ValidatorInfoCommission `json:"commission"`

	// consensus pubkey
	// Required: true
	ConsensusPubkey *string `json:"consensus_pubkey"`

	// description
	// Required: true
	Description *ValidatorInfoDescription `json:"description"`

	// jailed
	// Required: true
	Jailed *bool `json:"jailed"`
}

// Validate validates this validator info
func (m *ValidatorInfo) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateCommission(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateConsensusPubkey(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateDescription(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateJailed(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ValidatorInfo) validateCommission(formats strfmt.Registry) error {

	if err := validate.Required("commission", "body", m.Commission); err != nil {
		return err
	}

	if m.Commission != nil {
		if err := m.Commission.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("commission")
			}
			return err
		}
	}

	return nil
}

func (m *ValidatorInfo) validateConsensusPubkey(formats strfmt.Registry) error {

	if err := validate.Required("consensus_pubkey", "body", m.ConsensusPubkey); err != nil {
		return err
	}

	return nil
}

func (m *ValidatorInfo) validateDescription(formats strfmt.Registry) error {

	if err := validate.Required("description", "body", m.Description); err != nil {
		return err
	}

	if m.Description != nil {
		if err := m.Description.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("description")
			}
			return err
		}
	}

	return nil
}

func (m *ValidatorInfo) validateJailed(formats strfmt.Registry) error {

	if err := validate.Required("jailed", "body", m.Jailed); err != nil {
		return err
	}

	return nil
}

// ContextValidate validate this validator info based on the context it is used
func (m *ValidatorInfo) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateCommission(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateDescription(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ValidatorInfo) contextValidateCommission(ctx context.Context, formats strfmt.Registry) error {

	if m.Commission != nil {
		if err := m.Commission.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("commission")
			}
			return err
		}
	}

	return nil
}

func (m *ValidatorInfo) contextValidateDescription(ctx context.Context, formats strfmt.Registry) error {

	if m.Description != nil {
		if err := m.Description.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("description")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *ValidatorInfo) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ValidatorInfo) UnmarshalBinary(b []byte) error {
	var res ValidatorInfo
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}

// ValidatorInfoCommission validator info commission
//
// swagger:model ValidatorInfoCommission
type ValidatorInfoCommission struct {

	// commission rates
	// Required: true
	CommissionRates *ValidatorInfoCommissionCommissionRates `json:"commission_rates"`
}

// Validate validates this validator info commission
func (m *ValidatorInfoCommission) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateCommissionRates(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ValidatorInfoCommission) validateCommissionRates(formats strfmt.Registry) error {

	if err := validate.Required("commission"+"."+"commission_rates", "body", m.CommissionRates); err != nil {
		return err
	}

	if m.CommissionRates != nil {
		if err := m.CommissionRates.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("commission" + "." + "commission_rates")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this validator info commission based on the context it is used
func (m *ValidatorInfoCommission) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateCommissionRates(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ValidatorInfoCommission) contextValidateCommissionRates(ctx context.Context, formats strfmt.Registry) error {

	if m.CommissionRates != nil {
		if err := m.CommissionRates.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("commission" + "." + "commission_rates")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *ValidatorInfoCommission) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ValidatorInfoCommission) UnmarshalBinary(b []byte) error {
	var res ValidatorInfoCommission
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}

// ValidatorInfoCommissionCommissionRates validator info commission commission rates
//
// swagger:model ValidatorInfoCommissionCommissionRates
type ValidatorInfoCommissionCommissionRates struct {

	// rate
	// Required: true
	Rate *string `json:"rate"`
}

// Validate validates this validator info commission commission rates
func (m *ValidatorInfoCommissionCommissionRates) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateRate(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ValidatorInfoCommissionCommissionRates) validateRate(formats strfmt.Registry) error {

	if err := validate.Required("commission"+"."+"commission_rates"+"."+"rate", "body", m.Rate); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this validator info commission commission rates based on context it is used
func (m *ValidatorInfoCommissionCommissionRates) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ValidatorInfoCommissionCommissionRates) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ValidatorInfoCommissionCommissionRates) UnmarshalBinary(b []byte) error {
	var res ValidatorInfoCommissionCommissionRates
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}

// ValidatorInfoDescription validator info description
//
// swagger:model ValidatorInfoDescription
type ValidatorInfoDescription struct {

	// moniker
	Moniker string `json:"moniker,omitempty"`
}

// Validate validates this validator info description
func (m *ValidatorInfoDescription) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this validator info description based on context it is used
func (m *ValidatorInfoDescription) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ValidatorInfoDescription) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ValidatorInfoDescription) UnmarshalBinary(b []byte) error {
	var res ValidatorInfoDescription
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
