// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// ValidatorInfo validator info
// swagger:model ValidatorInfo
type ValidatorInfo struct {

	// consensus pubkey
	// Required: true
	ConsensusPubkey *string `json:"consensus_pubkey"`
}

// Validate validates this validator info
func (m *ValidatorInfo) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateConsensusPubkey(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ValidatorInfo) validateConsensusPubkey(formats strfmt.Registry) error {

	if err := validate.Required("consensus_pubkey", "body", m.ConsensusPubkey); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *ValidatorInfo) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ValidatorInfo) UnmarshalBinary(b []byte) error {
	var res ValidatorInfo
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
