// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
)

// ValidatorAddress bech32 encoded address
// Example: terravaloper1wg2mlrxdmnnkkykgqg4znky86nyrtc45q7a85l
//
// swagger:model ValidatorAddress
type ValidatorAddress string

// Validate validates this validator address
func (m ValidatorAddress) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this validator address based on context it is used
func (m ValidatorAddress) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}
