{
 "title": "Lido monitors",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Validators Commission Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "targets": [
    { "expr": "validators_commission * 100", "legendFormat": "{{label}}" }
   ]
  },
  {
   "title": "contracts parameters monitoring",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 }
  },
  {
   "title": "Hub parameters",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 9 },
   "targets": [
    { "expr": "hub_parameters_epoch_period{}", "legendFormat": "Epoch period" },
    {
     "expr": "hub_parameters_unbonding_period{}",
     "legendFormat": "Unbonding period"
    }
   ]
  },
  {
   "title": "Hub er threshold",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 9 },
   "targets": [
    { "expr": "hub_parameters_er_threshold{}", "legendFormat": "Er threshold" }
   ]
  },
  {
   "title": "Hub peg recovery fee",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 9 },
   "targets": [
    {
     "expr": "hub_parameters_peg_recovery_fee{}",
     "legendFormat": "Peg recovery fee"
    }
   ]
  },
  {
   "title": "crc32 sums of config data",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 17 },
   "targets": [
    { "expr": "airdrop_registry_config_crc32", "legendFormat": "airdrop registry config" },
    { "expr": "bluna_reward_config_crc32{}", "legendFormat": "bluna reward config" },
    { "expr": "hub_config_crc32{}", "legendFormat": "hub config" },
    { "expr": "hub_parameters_crc32{}", "legendFormat": "hub parameters" },
    {
     "expr": "reward_dispatcher_config_crc32{}",
     "legendFormat": "reward dispatcher config"
    },
    {
     "expr": "validators_registry_config_crc32{}",
     "legendFormat": "validators registry config"
    }
   ]
  },
  {
   "title": "Whitelisted validators CRC32",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 17 },
   "targets": [
    { "expr": "whitelisted_validators_crc32{}", "legendFormat": "whitelisted validators crc32" }
   ]
  },
  {
   "title": "Number of whitelisted validators",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 17 },
   "targets": [
    {
     "expr": "whitelisted_validators_num",
     "legendFormat": "number of whitelisted validators"
    }
   ]
  },
  { "title": "contracts state monitoring", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Slashing: Jailed Validators",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "slashing_num_jailed_validators{}",
     "legendFormat": "currently jailed validators"
    }
   ]
  },
  {
   "title": "Slashing: Missed Blocks",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 26 },
   "targets": [
    { "expr": "slashing_num_missed_blocks{}", "legendFormat": "{{label}}" }
   ]
  },
  {
   "title": "Slashing: Tombstoned Validators",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 26 },
   "targets": [
    {
     "expr": "slashing_num_tombstoned_validators{}",
     "legendFormat": "currently tombstoned validators"
    }
   ]
  },
  {
   "title": "update global index fees",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 34 },
   "targets": [
    { "expr": "update_global_index_gas_used{}", "legendFormat": "gas used" },
    {
     "expr": "update_global_index_gas_wanted{}",
     "legendFormat": "gas wanted"
    },
    { "expr": "update_global_index_uusd_fee{}", "legendFormat": "uusd fee" }
   ]
  },
  {
   "title": "update global index transactions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 34 },
   "targets": [
    {
     "expr": "update_global_index_failed_tx_since_last_check{}",
     "legendFormat": "failed txs since last check"
    },
    {
     "expr": "update_global_index_successful_tx_since_last_check{}",
     "legendFormat": "successful txs since last check"
    }
   ]
  },
  {
   "title": "bLuna Exchange Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 34 },
   "targets": [
    { "expr": "bluna_exchange_rate{}", "legendFormat": "exchange rate" }
   ]
  }
 ]
}