// Code generated by go-swagger; DO NOT EDIT.

package client

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/runtime"
	httptransport "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/lidofinance/terra-monitors/openapi/client/bank"
	"github.com/lidofinance/terra-monitors/openapi/client/oracle"
	"github.com/lidofinance/terra-monitors/openapi/client/query"
	"github.com/lidofinance/terra-monitors/openapi/client/transactions"
	"github.com/lidofinance/terra-monitors/openapi/client/wasm"
)

// Default terra lite for terra HTTP client.
var Default = NewHTTPClient(nil)

const (
	// DefaultHost is the default Host
	// found in Meta (info) section of spec file
	DefaultHost string = "fcd.terra.dev"
	// DefaultBasePath is the default BasePath
	// found in Meta (info) section of spec file
	DefaultBasePath string = "/"
)

// DefaultSchemes are the default schemes found in Meta (info) section of spec file
var DefaultSchemes = []string{"https"}

// NewHTTPClient creates a new terra lite for terra HTTP client.
func NewHTTPClient(formats strfmt.Registry) *TerraLiteForTerra {
	return NewHTTPClientWithConfig(formats, nil)
}

// NewHTTPClientWithConfig creates a new terra lite for terra HTTP client,
// using a customizable transport config.
func NewHTTPClientWithConfig(formats strfmt.Registry, cfg *TransportConfig) *TerraLiteForTerra {
	// ensure nullable parameters have default
	if cfg == nil {
		cfg = DefaultTransportConfig()
	}

	// create transport and client
	transport := httptransport.New(cfg.Host, cfg.BasePath, cfg.Schemes)
	return New(transport, formats)
}

// New creates a new terra lite for terra client
func New(transport runtime.ClientTransport, formats strfmt.Registry) *TerraLiteForTerra {
	// ensure nullable parameters have default
	if formats == nil {
		formats = strfmt.Default
	}

	cli := new(TerraLiteForTerra)
	cli.Transport = transport
	cli.Bank = bank.New(transport, formats)
	cli.Oracle = oracle.New(transport, formats)
	cli.Query = query.New(transport, formats)
	cli.Transactions = transactions.New(transport, formats)
	cli.Wasm = wasm.New(transport, formats)
	return cli
}

// DefaultTransportConfig creates a TransportConfig with the
// default settings taken from the meta section of the spec file.
func DefaultTransportConfig() *TransportConfig {
	return &TransportConfig{
		Host:     DefaultHost,
		BasePath: DefaultBasePath,
		Schemes:  DefaultSchemes,
	}
}

// TransportConfig contains the transport related info,
// found in the meta section of the spec file.
type TransportConfig struct {
	Host     string
	BasePath string
	Schemes  []string
}

// WithHost overrides the default host,
// provided by the meta section of the spec file.
func (cfg *TransportConfig) WithHost(host string) *TransportConfig {
	cfg.Host = host
	return cfg
}

// WithBasePath overrides the default basePath,
// provided by the meta section of the spec file.
func (cfg *TransportConfig) WithBasePath(basePath string) *TransportConfig {
	cfg.BasePath = basePath
	return cfg
}

// WithSchemes overrides the default schemes,
// provided by the meta section of the spec file.
func (cfg *TransportConfig) WithSchemes(schemes []string) *TransportConfig {
	cfg.Schemes = schemes
	return cfg
}

// TerraLiteForTerra is a client for terra lite for terra
type TerraLiteForTerra struct {
	Bank bank.ClientService

	Oracle oracle.ClientService

	Query query.ClientService

	Transactions transactions.ClientService

	Wasm wasm.ClientService

	Transport runtime.ClientTransport
}

// SetTransport changes the transport on the client and all its subresources
func (c *TerraLiteForTerra) SetTransport(transport runtime.ClientTransport) {
	c.Transport = transport
	c.Bank.SetTransport(transport)
	c.Oracle.SetTransport(transport)
	c.Query.SetTransport(transport)
	c.Transactions.SetTransport(transport)
	c.Wasm.SetTransport(transport)
}
