{
 "title": "GovernanceBot",
 "description": "Metrics for governance bot. See https://github.com/lidofinance/terra-bots for more",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Memory allocated now",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "go_memstats_mallocs_total{instance=\"governance_bot:8080\"} - go_memstats_frees_total{instance=\"governance_bot:8080\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "CPU usage %",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "irate(process_cpu_seconds_total{instance=\"governance_bot:8080\"}[5m]) * 100",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Governance bot failed requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "rate(governance_bot_failed_requests{}[60m])"
    }
   ]
  }
 ]
}