// Code generated by go-swagger; DO NOT EDIT.

package transactions

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetStakingValidatorsValidatorAddrParams creates a new GetStakingValidatorsValidatorAddrParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetStakingValidatorsValidatorAddrParams() *GetStakingValidatorsValidatorAddrParams {
	return &GetStakingValidatorsValidatorAddrParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetStakingValidatorsValidatorAddrParamsWithTimeout creates a new GetStakingValidatorsValidatorAddrParams object
// with the ability to set a timeout on a request.
func NewGetStakingValidatorsValidatorAddrParamsWithTimeout(timeout time.Duration) *GetStakingValidatorsValidatorAddrParams {
	return &GetStakingValidatorsValidatorAddrParams{
		timeout: timeout,
	}
}

// NewGetStakingValidatorsValidatorAddrParamsWithContext creates a new GetStakingValidatorsValidatorAddrParams object
// with the ability to set a context for a request.
func NewGetStakingValidatorsValidatorAddrParamsWithContext(ctx context.Context) *GetStakingValidatorsValidatorAddrParams {
	return &GetStakingValidatorsValidatorAddrParams{
		Context: ctx,
	}
}

// NewGetStakingValidatorsValidatorAddrParamsWithHTTPClient creates a new GetStakingValidatorsValidatorAddrParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetStakingValidatorsValidatorAddrParamsWithHTTPClient(client *http.Client) *GetStakingValidatorsValidatorAddrParams {
	return &GetStakingValidatorsValidatorAddrParams{
		HTTPClient: client,
	}
}

/* GetStakingValidatorsValidatorAddrParams contains all the parameters to send to the API endpoint
   for the get staking validators validator addr operation.

   Typically these are written to a http.Request.
*/
type GetStakingValidatorsValidatorAddrParams struct {

	/* ValidatorAddr.

	   validator address
	*/
	ValidatorAddr string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get staking validators validator addr params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetStakingValidatorsValidatorAddrParams) WithDefaults() *GetStakingValidatorsValidatorAddrParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get staking validators validator addr params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetStakingValidatorsValidatorAddrParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get staking validators validator addr params
func (o *GetStakingValidatorsValidatorAddrParams) WithTimeout(timeout time.Duration) *GetStakingValidatorsValidatorAddrParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get staking validators validator addr params
func (o *GetStakingValidatorsValidatorAddrParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get staking validators validator addr params
func (o *GetStakingValidatorsValidatorAddrParams) WithContext(ctx context.Context) *GetStakingValidatorsValidatorAddrParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get staking validators validator addr params
func (o *GetStakingValidatorsValidatorAddrParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get staking validators validator addr params
func (o *GetStakingValidatorsValidatorAddrParams) WithHTTPClient(client *http.Client) *GetStakingValidatorsValidatorAddrParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get staking validators validator addr params
func (o *GetStakingValidatorsValidatorAddrParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithValidatorAddr adds the validatorAddr to the get staking validators validator addr params
func (o *GetStakingValidatorsValidatorAddrParams) WithValidatorAddr(validatorAddr string) *GetStakingValidatorsValidatorAddrParams {
	o.SetValidatorAddr(validatorAddr)
	return o
}

// SetValidatorAddr adds the validatorAddr to the get staking validators validator addr params
func (o *GetStakingValidatorsValidatorAddrParams) SetValidatorAddr(validatorAddr string) {
	o.ValidatorAddr = validatorAddr
}

// WriteToRequest writes these params to a swagger request
func (o *GetStakingValidatorsValidatorAddrParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param validatorAddr
	if err := r.SetPathParam("validatorAddr", o.ValidatorAddr); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
