// Code generated by go-swagger; DO NOT EDIT.

package transactions

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/lidofinance/terra-monitors/openapi/models"
)

// GetStakingValidatorsValidatorAddrReader is a Reader for the GetStakingValidatorsValidatorAddr structure.
type GetStakingValidatorsValidatorAddrReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetStakingValidatorsValidatorAddrReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetStakingValidatorsValidatorAddrOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewGetStakingValidatorsValidatorAddrBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetStakingValidatorsValidatorAddrOK creates a GetStakingValidatorsValidatorAddrOK with default headers values
func NewGetStakingValidatorsValidatorAddrOK() *GetStakingValidatorsValidatorAddrOK {
	return &GetStakingValidatorsValidatorAddrOK{}
}

/*GetStakingValidatorsValidatorAddrOK handles this case with default header values.

Success
*/
type GetStakingValidatorsValidatorAddrOK struct {
	Payload *GetStakingValidatorsValidatorAddrOKBody
}

func (o *GetStakingValidatorsValidatorAddrOK) Error() string {
	return fmt.Sprintf("[GET /staking/validators/{validatorAddr}][%d] getStakingValidatorsValidatorAddrOK  %+v", 200, o.Payload)
}

func (o *GetStakingValidatorsValidatorAddrOK) GetPayload() *GetStakingValidatorsValidatorAddrOKBody {
	return o.Payload
}

func (o *GetStakingValidatorsValidatorAddrOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(GetStakingValidatorsValidatorAddrOKBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetStakingValidatorsValidatorAddrBadRequest creates a GetStakingValidatorsValidatorAddrBadRequest with default headers values
func NewGetStakingValidatorsValidatorAddrBadRequest() *GetStakingValidatorsValidatorAddrBadRequest {
	return &GetStakingValidatorsValidatorAddrBadRequest{}
}

/*GetStakingValidatorsValidatorAddrBadRequest handles this case with default header values.

Error
*/
type GetStakingValidatorsValidatorAddrBadRequest struct {
	Payload *GetStakingValidatorsValidatorAddrBadRequestBody
}

func (o *GetStakingValidatorsValidatorAddrBadRequest) Error() string {
	return fmt.Sprintf("[GET /staking/validators/{validatorAddr}][%d] getStakingValidatorsValidatorAddrBadRequest  %+v", 400, o.Payload)
}

func (o *GetStakingValidatorsValidatorAddrBadRequest) GetPayload() *GetStakingValidatorsValidatorAddrBadRequestBody {
	return o.Payload
}

func (o *GetStakingValidatorsValidatorAddrBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(GetStakingValidatorsValidatorAddrBadRequestBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*GetStakingValidatorsValidatorAddrBadRequestBody get staking validators validator addr bad request body
swagger:model GetStakingValidatorsValidatorAddrBadRequestBody
*/
type GetStakingValidatorsValidatorAddrBadRequestBody struct {

	// code
	Code float64 `json:"code,omitempty"`

	// message
	Message string `json:"message,omitempty"`

	// type
	Type string `json:"type,omitempty"`
}

// Validate validates this get staking validators validator addr bad request body
func (o *GetStakingValidatorsValidatorAddrBadRequestBody) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *GetStakingValidatorsValidatorAddrBadRequestBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetStakingValidatorsValidatorAddrBadRequestBody) UnmarshalBinary(b []byte) error {
	var res GetStakingValidatorsValidatorAddrBadRequestBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*GetStakingValidatorsValidatorAddrOKBody get staking validators validator addr o k body
swagger:model GetStakingValidatorsValidatorAddrOKBody
*/
type GetStakingValidatorsValidatorAddrOKBody struct {

	// height
	Height string `json:"height,omitempty"`

	// result
	Result *models.ValidatorInfo `json:"result,omitempty"`
}

// Validate validates this get staking validators validator addr o k body
func (o *GetStakingValidatorsValidatorAddrOKBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateResult(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *GetStakingValidatorsValidatorAddrOKBody) validateResult(formats strfmt.Registry) error {

	if swag.IsZero(o.Result) { // not required
		return nil
	}

	if o.Result != nil {
		if err := o.Result.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("getStakingValidatorsValidatorAddrOK" + "." + "result")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (o *GetStakingValidatorsValidatorAddrOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetStakingValidatorsValidatorAddrOKBody) UnmarshalBinary(b []byte) error {
	var res GetStakingValidatorsValidatorAddrOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
