# my global config
global:
  scrape_interval:     1m # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  scrape_timeout: 30s

scrape_configs:
  - job_name: lido_terra
    scrape_interval: 1m
    static_configs:
    - targets: ['lido_terra:8080', 'governance_bot:8080']
