{
 "title": "Bots",
 "description": "Metrics for bots. See https://github.com/lidofinance/terra-bots for more",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Update global index bot", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "update global index fees",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "targets": [
    { "expr": "update_global_index_gas_used{}", "legendFormat": "gas used" },
    {
     "expr": "update_global_index_gas_wanted{}",
     "legendFormat": "gas wanted"
    },
    { "expr": "update_global_index_uusd_fee{}", "legendFormat": "uusd fee" }
   ]
  },
  {
   "title": "update global index transactions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
   "targets": [
    {
     "expr": "update_global_index_failed_tx_since_last_check{}",
     "legendFormat": "failed txs since last check"
    },
    {
     "expr": "update_global_index_successful_tx_since_last_check{}",
     "legendFormat": "successful txs since last check"
    }
   ]
  },
  {
   "title": "Operator bot balance",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "targets": [
    { "expr": "operator_bot_balance", "legendFormat": "bot balance" }
   ]
  },
  { "title": "Governance bot", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Memory allocated now",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "go_memstats_mallocs_total{instance=\"governance_bot:8080\"} - go_memstats_frees_total{instance=\"governance_bot:8080\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "CPU usage %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "irate(process_cpu_seconds_total{instance=\"governance_bot:8080\"}[5m]) * 100",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Governance bot failed requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 18 },
   "targets": [
    {
     "expr": "rate(governance_bot_failed_requests{}[60m])"
    }
   ]
  }
 ]
}