// Code generated by go-swagger; DO NOT EDIT.

package transactions

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// New creates a new transactions API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) ClientService {
	return &Client{transport: transport, formats: formats}
}

/*
Client for transactions API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

// ClientOption is the option for Client methods
type ClientOption func(*runtime.ClientOperation)

// ClientService is the interface for Client methods
type ClientService interface {
	GetStakingValidatorsValidatorAddr(params *GetStakingValidatorsValidatorAddrParams, opts ...ClientOption) (*GetStakingValidatorsValidatorAddrOK, error)

	GetV1Txs(params *GetV1TxsParams, opts ...ClientOption) (*GetV1TxsOK, error)

	SetTransport(transport runtime.ClientTransport)
}

/*
  GetStakingValidatorsValidatorAddr gets validator info

  Get validator info
*/
func (a *Client) GetStakingValidatorsValidatorAddr(params *GetStakingValidatorsValidatorAddrParams, opts ...ClientOption) (*GetStakingValidatorsValidatorAddrOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetStakingValidatorsValidatorAddrParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "GetStakingValidatorsValidatorAddr",
		Method:             "GET",
		PathPattern:        "/staking/validators/{validatorAddr}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &GetStakingValidatorsValidatorAddrReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*GetStakingValidatorsValidatorAddrOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for GetStakingValidatorsValidatorAddr: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
  GetV1Txs gets tx list

  Get Tx List
*/
func (a *Client) GetV1Txs(params *GetV1TxsParams, opts ...ClientOption) (*GetV1TxsOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetV1TxsParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "GetV1Txs",
		Method:             "GET",
		PathPattern:        "/v1/txs",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &GetV1TxsReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*GetV1TxsOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for GetV1Txs: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
