// Code generated by go-swagger; DO NOT EDIT.

package query

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewDelegatorDelegationsParams creates a new DelegatorDelegationsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewDelegatorDelegationsParams() *DelegatorDelegationsParams {
	return &DelegatorDelegationsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewDelegatorDelegationsParamsWithTimeout creates a new DelegatorDelegationsParams object
// with the ability to set a timeout on a request.
func NewDelegatorDelegationsParamsWithTimeout(timeout time.Duration) *DelegatorDelegationsParams {
	return &DelegatorDelegationsParams{
		timeout: timeout,
	}
}

// NewDelegatorDelegationsParamsWithContext creates a new DelegatorDelegationsParams object
// with the ability to set a context for a request.
func NewDelegatorDelegationsParamsWithContext(ctx context.Context) *DelegatorDelegationsParams {
	return &DelegatorDelegationsParams{
		Context: ctx,
	}
}

// NewDelegatorDelegationsParamsWithHTTPClient creates a new DelegatorDelegationsParams object
// with the ability to set a custom HTTPClient for a request.
func NewDelegatorDelegationsParamsWithHTTPClient(client *http.Client) *DelegatorDelegationsParams {
	return &DelegatorDelegationsParams{
		HTTPClient: client,
	}
}

/* DelegatorDelegationsParams contains all the parameters to send to the API endpoint
   for the delegator delegations operation.

   Typically these are written to a http.Request.
*/
type DelegatorDelegationsParams struct {

	/* DelegatorAddr.

	   delegator_addr defines the delegator address to query for.
	*/
	DelegatorAddr string

	/* PaginationCountTotal.

	     count_total is set to true  to indicate that the result set should include
	a count of the total number of items available for pagination in UIs.
	count_total is only respected when offset is used. It is ignored when key
	is set.

	     Format: boolean
	*/
	PaginationCountTotal *bool

	/* PaginationKey.

	     key is a value returned in PageResponse.next_key to begin
	querying the next page most efficiently. Only one of offset or key
	should be set.

	     Format: byte
	*/
	PaginationKey *strfmt.Base64

	/* PaginationLimit.

	     limit is the total number of results to be returned in the result page.
	If left empty it will default to a value to be set by each app.

	     Format: uint64
	*/
	PaginationLimit *string

	/* PaginationOffset.

	     offset is a numeric offset that can be used when key is unavailable.
	It is less efficient than using key. Only one of offset or key should
	be set.

	     Format: uint64
	*/
	PaginationOffset *string

	/* PaginationReverse.

	   reverse is set to true if results are to be returned in the descending order.

	   Format: boolean
	*/
	PaginationReverse *bool

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the delegator delegations params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DelegatorDelegationsParams) WithDefaults() *DelegatorDelegationsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the delegator delegations params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DelegatorDelegationsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the delegator delegations params
func (o *DelegatorDelegationsParams) WithTimeout(timeout time.Duration) *DelegatorDelegationsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delegator delegations params
func (o *DelegatorDelegationsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delegator delegations params
func (o *DelegatorDelegationsParams) WithContext(ctx context.Context) *DelegatorDelegationsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delegator delegations params
func (o *DelegatorDelegationsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delegator delegations params
func (o *DelegatorDelegationsParams) WithHTTPClient(client *http.Client) *DelegatorDelegationsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delegator delegations params
func (o *DelegatorDelegationsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithDelegatorAddr adds the delegatorAddr to the delegator delegations params
func (o *DelegatorDelegationsParams) WithDelegatorAddr(delegatorAddr string) *DelegatorDelegationsParams {
	o.SetDelegatorAddr(delegatorAddr)
	return o
}

// SetDelegatorAddr adds the delegatorAddr to the delegator delegations params
func (o *DelegatorDelegationsParams) SetDelegatorAddr(delegatorAddr string) {
	o.DelegatorAddr = delegatorAddr
}

// WithPaginationCountTotal adds the paginationCountTotal to the delegator delegations params
func (o *DelegatorDelegationsParams) WithPaginationCountTotal(paginationCountTotal *bool) *DelegatorDelegationsParams {
	o.SetPaginationCountTotal(paginationCountTotal)
	return o
}

// SetPaginationCountTotal adds the paginationCountTotal to the delegator delegations params
func (o *DelegatorDelegationsParams) SetPaginationCountTotal(paginationCountTotal *bool) {
	o.PaginationCountTotal = paginationCountTotal
}

// WithPaginationKey adds the paginationKey to the delegator delegations params
func (o *DelegatorDelegationsParams) WithPaginationKey(paginationKey *strfmt.Base64) *DelegatorDelegationsParams {
	o.SetPaginationKey(paginationKey)
	return o
}

// SetPaginationKey adds the paginationKey to the delegator delegations params
func (o *DelegatorDelegationsParams) SetPaginationKey(paginationKey *strfmt.Base64) {
	o.PaginationKey = paginationKey
}

// WithPaginationLimit adds the paginationLimit to the delegator delegations params
func (o *DelegatorDelegationsParams) WithPaginationLimit(paginationLimit *string) *DelegatorDelegationsParams {
	o.SetPaginationLimit(paginationLimit)
	return o
}

// SetPaginationLimit adds the paginationLimit to the delegator delegations params
func (o *DelegatorDelegationsParams) SetPaginationLimit(paginationLimit *string) {
	o.PaginationLimit = paginationLimit
}

// WithPaginationOffset adds the paginationOffset to the delegator delegations params
func (o *DelegatorDelegationsParams) WithPaginationOffset(paginationOffset *string) *DelegatorDelegationsParams {
	o.SetPaginationOffset(paginationOffset)
	return o
}

// SetPaginationOffset adds the paginationOffset to the delegator delegations params
func (o *DelegatorDelegationsParams) SetPaginationOffset(paginationOffset *string) {
	o.PaginationOffset = paginationOffset
}

// WithPaginationReverse adds the paginationReverse to the delegator delegations params
func (o *DelegatorDelegationsParams) WithPaginationReverse(paginationReverse *bool) *DelegatorDelegationsParams {
	o.SetPaginationReverse(paginationReverse)
	return o
}

// SetPaginationReverse adds the paginationReverse to the delegator delegations params
func (o *DelegatorDelegationsParams) SetPaginationReverse(paginationReverse *bool) {
	o.PaginationReverse = paginationReverse
}

// WriteToRequest writes these params to a swagger request
func (o *DelegatorDelegationsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param delegator_addr
	if err := r.SetPathParam("delegator_addr", o.DelegatorAddr); err != nil {
		return err
	}

	if o.PaginationCountTotal != nil {

		// query param pagination.count_total
		var qrPaginationCountTotal bool

		if o.PaginationCountTotal != nil {
			qrPaginationCountTotal = *o.PaginationCountTotal
		}
		qPaginationCountTotal := swag.FormatBool(qrPaginationCountTotal)
		if qPaginationCountTotal != "" {

			if err := r.SetQueryParam("pagination.count_total", qPaginationCountTotal); err != nil {
				return err
			}
		}
	}

	if o.PaginationKey != nil {

		// query param pagination.key
		var qrPaginationKey strfmt.Base64

		if o.PaginationKey != nil {
			qrPaginationKey = *o.PaginationKey
		}
		qPaginationKey := qrPaginationKey.String()
		if qPaginationKey != "" {

			if err := r.SetQueryParam("pagination.key", qPaginationKey); err != nil {
				return err
			}
		}
	}

	if o.PaginationLimit != nil {

		// query param pagination.limit
		var qrPaginationLimit string

		if o.PaginationLimit != nil {
			qrPaginationLimit = *o.PaginationLimit
		}
		qPaginationLimit := qrPaginationLimit
		if qPaginationLimit != "" {

			if err := r.SetQueryParam("pagination.limit", qPaginationLimit); err != nil {
				return err
			}
		}
	}

	if o.PaginationOffset != nil {

		// query param pagination.offset
		var qrPaginationOffset string

		if o.PaginationOffset != nil {
			qrPaginationOffset = *o.PaginationOffset
		}
		qPaginationOffset := qrPaginationOffset
		if qPaginationOffset != "" {

			if err := r.SetQueryParam("pagination.offset", qPaginationOffset); err != nil {
				return err
			}
		}
	}

	if o.PaginationReverse != nil {

		// query param pagination.reverse
		var qrPaginationReverse bool

		if o.PaginationReverse != nil {
			qrPaginationReverse = *o.PaginationReverse
		}
		qPaginationReverse := swag.FormatBool(qrPaginationReverse)
		if qPaginationReverse != "" {

			if err := r.SetQueryParam("pagination.reverse", qPaginationReverse); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
