// Code generated by go-swagger; DO NOT EDIT.

package query

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"fmt"
	"io"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// DelegatorDelegationsReader is a Reader for the DelegatorDelegations structure.
type DelegatorDelegationsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DelegatorDelegationsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewDelegatorDelegationsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewDelegatorDelegationsDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewDelegatorDelegationsOK creates a DelegatorDelegationsOK with default headers values
func NewDelegatorDelegationsOK() *DelegatorDelegationsOK {
	return &DelegatorDelegationsOK{}
}

/* DelegatorDelegationsOK describes a response with status code 200, with default header values.

A successful response.
*/
type DelegatorDelegationsOK struct {
	Payload *DelegatorDelegationsOKBody
}

func (o *DelegatorDelegationsOK) Error() string {
	return fmt.Sprintf("[GET /cosmos/staking/v1beta1/delegations/{delegator_addr}][%d] delegatorDelegationsOK  %+v", 200, o.Payload)
}
func (o *DelegatorDelegationsOK) GetPayload() *DelegatorDelegationsOKBody {
	return o.Payload
}

func (o *DelegatorDelegationsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(DelegatorDelegationsOKBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDelegatorDelegationsDefault creates a DelegatorDelegationsDefault with default headers values
func NewDelegatorDelegationsDefault(code int) *DelegatorDelegationsDefault {
	return &DelegatorDelegationsDefault{
		_statusCode: code,
	}
}

/* DelegatorDelegationsDefault describes a response with status code -1, with default header values.

An unexpected error response
*/
type DelegatorDelegationsDefault struct {
	_statusCode int

	Payload *DelegatorDelegationsDefaultBody
}

// Code gets the status code for the delegator delegations default response
func (o *DelegatorDelegationsDefault) Code() int {
	return o._statusCode
}

func (o *DelegatorDelegationsDefault) Error() string {
	return fmt.Sprintf("[GET /cosmos/staking/v1beta1/delegations/{delegator_addr}][%d] DelegatorDelegations default  %+v", o._statusCode, o.Payload)
}
func (o *DelegatorDelegationsDefault) GetPayload() *DelegatorDelegationsDefaultBody {
	return o.Payload
}

func (o *DelegatorDelegationsDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(DelegatorDelegationsDefaultBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*DelegatorDelegationsDefaultBody delegator delegations default body
swagger:model DelegatorDelegationsDefaultBody
*/
type DelegatorDelegationsDefaultBody struct {

	// code
	Code int32 `json:"code,omitempty"`

	// details
	Details []*DelegatorDelegationsDefaultBodyDetailsItems0 `json:"details"`

	// error
	Error string `json:"error,omitempty"`

	// message
	Message string `json:"message,omitempty"`
}

// Validate validates this delegator delegations default body
func (o *DelegatorDelegationsDefaultBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateDetails(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *DelegatorDelegationsDefaultBody) validateDetails(formats strfmt.Registry) error {
	if swag.IsZero(o.Details) { // not required
		return nil
	}

	for i := 0; i < len(o.Details); i++ {
		if swag.IsZero(o.Details[i]) { // not required
			continue
		}

		if o.Details[i] != nil {
			if err := o.Details[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("DelegatorDelegations default" + "." + "details" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this delegator delegations default body based on the context it is used
func (o *DelegatorDelegationsDefaultBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := o.contextValidateDetails(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *DelegatorDelegationsDefaultBody) contextValidateDetails(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(o.Details); i++ {

		if o.Details[i] != nil {
			if err := o.Details[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("DelegatorDelegations default" + "." + "details" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (o *DelegatorDelegationsDefaultBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *DelegatorDelegationsDefaultBody) UnmarshalBinary(b []byte) error {
	var res DelegatorDelegationsDefaultBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*DelegatorDelegationsDefaultBodyDetailsItems0 `Any` contains an arbitrary serialized protocol buffer message along with a
// URL that describes the type of the serialized message.
//
// Protobuf library provides support to pack/unpack Any values in the form
// of utility functions or additional generated methods of the Any type.
//
// Example 1: Pack and unpack a message in C++.
//
//     Foo foo = ...;
//     Any any;
//     any.PackFrom(foo);
//     ...
//     if (any.UnpackTo(&foo)) {
//       ...
//     }
//
// Example 2: Pack and unpack a message in Java.
//
//     Foo foo = ...;
//     Any any = Any.pack(foo);
//     ...
//     if (any.is(Foo.class)) {
//       foo = any.unpack(Foo.class);
//     }
//
//  Example 3: Pack and unpack a message in Python.
//
//     foo = Foo(...)
//     any = Any()
//     any.Pack(foo)
//     ...
//     if any.Is(Foo.DESCRIPTOR):
//       any.Unpack(foo)
//       ...
//
//  Example 4: Pack and unpack a message in Go
//
//      foo := &pb.Foo{...}
//      any, err := ptypes.MarshalAny(foo)
//      ...
//      foo := &pb.Foo{}
//      if err := ptypes.UnmarshalAny(any, foo); err != nil {
//        ...
//      }
//
// The pack methods provided by protobuf library will by default use
// 'type.googleapis.com/full.type.name' as the type URL and the unpack
// methods only use the fully qualified type name after the last '/'
// in the type URL, for example "foo.bar.com/x/y.z" will yield type
// name "y.z".
//
//
// JSON
// ====
// The JSON representation of an `Any` value uses the regular
// representation of the deserialized, embedded message, with an
// additional field `@type` which contains the type URL. Example:
//
//     package google.profile;
//     message Person {
//       string first_name = 1;
//       string last_name = 2;
//     }
//
//     {
//       "@type": "type.googleapis.com/google.profile.Person",
//       "firstName": <string>,
//       "lastName": <string>
//     }
//
// If the embedded message type is well-known and has a custom JSON
// representation, that representation will be embedded adding a field
// `value` which holds the custom JSON in addition to the `@type`
// field. Example (for message [google.protobuf.Duration][]):
//
//     {
//       "@type": "type.googleapis.com/google.protobuf.Duration",
//       "value": "1.212s"
//     }
swagger:model DelegatorDelegationsDefaultBodyDetailsItems0
*/
type DelegatorDelegationsDefaultBodyDetailsItems0 struct {

	// A URL/resource name that uniquely identifies the type of the serialized
	// protocol buffer message. This string must contain at least
	// one "/" character. The last segment of the URL's path must represent
	// the fully qualified name of the type (as in
	// `path/google.protobuf.Duration`). The name should be in a canonical form
	// (e.g., leading "." is not accepted).
	//
	// In practice, teams usually precompile into the binary all types that they
	// expect it to use in the context of Any. However, for URLs which use the
	// scheme `http`, `https`, or no scheme, one can optionally set up a type
	// server that maps type URLs to message definitions as follows:
	//
	// * If no scheme is provided, `https` is assumed.
	// * An HTTP GET on the URL must yield a [google.protobuf.Type][]
	//   value in binary format, or produce an error.
	// * Applications are allowed to cache lookup results based on the
	//   URL, or have them precompiled into a binary to avoid any
	//   lookup. Therefore, binary compatibility needs to be preserved
	//   on changes to types. (Use versioned type names to manage
	//   breaking changes.)
	//
	// Note: this functionality is not currently available in the official
	// protobuf release, and it is not used for type URLs beginning with
	// type.googleapis.com.
	//
	// Schemes other than `http`, `https` (or the empty scheme) might be
	// used with implementation specific semantics.
	TypeURL string `json:"type_url,omitempty"`

	// Must be a valid serialized protocol buffer of the above specified type.
	// Format: byte
	Value strfmt.Base64 `json:"value,omitempty"`
}

// Validate validates this delegator delegations default body details items0
func (o *DelegatorDelegationsDefaultBodyDetailsItems0) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this delegator delegations default body details items0 based on context it is used
func (o *DelegatorDelegationsDefaultBodyDetailsItems0) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *DelegatorDelegationsDefaultBodyDetailsItems0) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *DelegatorDelegationsDefaultBodyDetailsItems0) UnmarshalBinary(b []byte) error {
	var res DelegatorDelegationsDefaultBodyDetailsItems0
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*DelegatorDelegationsOKBody QueryDelegatorDelegationsResponse is response type for the
// Query/DelegatorDelegations RPC method.
swagger:model DelegatorDelegationsOKBody
*/
type DelegatorDelegationsOKBody struct {

	// delegation_responses defines all the delegations' info of a delegator.
	DelegationResponses []*DelegatorDelegationsOKBodyDelegationResponsesItems0 `json:"delegation_responses"`

	// pagination
	Pagination *DelegatorDelegationsOKBodyPagination `json:"pagination,omitempty"`
}

// Validate validates this delegator delegations o k body
func (o *DelegatorDelegationsOKBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateDelegationResponses(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validatePagination(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *DelegatorDelegationsOKBody) validateDelegationResponses(formats strfmt.Registry) error {
	if swag.IsZero(o.DelegationResponses) { // not required
		return nil
	}

	for i := 0; i < len(o.DelegationResponses); i++ {
		if swag.IsZero(o.DelegationResponses[i]) { // not required
			continue
		}

		if o.DelegationResponses[i] != nil {
			if err := o.DelegationResponses[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("delegatorDelegationsOK" + "." + "delegation_responses" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (o *DelegatorDelegationsOKBody) validatePagination(formats strfmt.Registry) error {
	if swag.IsZero(o.Pagination) { // not required
		return nil
	}

	if o.Pagination != nil {
		if err := o.Pagination.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("delegatorDelegationsOK" + "." + "pagination")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this delegator delegations o k body based on the context it is used
func (o *DelegatorDelegationsOKBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := o.contextValidateDelegationResponses(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := o.contextValidatePagination(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *DelegatorDelegationsOKBody) contextValidateDelegationResponses(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(o.DelegationResponses); i++ {

		if o.DelegationResponses[i] != nil {
			if err := o.DelegationResponses[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("delegatorDelegationsOK" + "." + "delegation_responses" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (o *DelegatorDelegationsOKBody) contextValidatePagination(ctx context.Context, formats strfmt.Registry) error {

	if o.Pagination != nil {
		if err := o.Pagination.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("delegatorDelegationsOK" + "." + "pagination")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (o *DelegatorDelegationsOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *DelegatorDelegationsOKBody) UnmarshalBinary(b []byte) error {
	var res DelegatorDelegationsOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*DelegatorDelegationsOKBodyDelegationResponsesItems0 DelegationResponse is equivalent to Delegation except that it contains a
// balance in addition to shares which is more suitable for client responses.
swagger:model DelegatorDelegationsOKBodyDelegationResponsesItems0
*/
type DelegatorDelegationsOKBodyDelegationResponsesItems0 struct {

	// balance
	Balance *DelegatorDelegationsOKBodyDelegationResponsesItems0Balance `json:"balance,omitempty"`

	// delegation
	Delegation *DelegatorDelegationsOKBodyDelegationResponsesItems0Delegation `json:"delegation,omitempty"`
}

// Validate validates this delegator delegations o k body delegation responses items0
func (o *DelegatorDelegationsOKBodyDelegationResponsesItems0) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateBalance(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateDelegation(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *DelegatorDelegationsOKBodyDelegationResponsesItems0) validateBalance(formats strfmt.Registry) error {
	if swag.IsZero(o.Balance) { // not required
		return nil
	}

	if o.Balance != nil {
		if err := o.Balance.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("balance")
			}
			return err
		}
	}

	return nil
}

func (o *DelegatorDelegationsOKBodyDelegationResponsesItems0) validateDelegation(formats strfmt.Registry) error {
	if swag.IsZero(o.Delegation) { // not required
		return nil
	}

	if o.Delegation != nil {
		if err := o.Delegation.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("delegation")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this delegator delegations o k body delegation responses items0 based on the context it is used
func (o *DelegatorDelegationsOKBodyDelegationResponsesItems0) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := o.contextValidateBalance(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := o.contextValidateDelegation(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *DelegatorDelegationsOKBodyDelegationResponsesItems0) contextValidateBalance(ctx context.Context, formats strfmt.Registry) error {

	if o.Balance != nil {
		if err := o.Balance.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("balance")
			}
			return err
		}
	}

	return nil
}

func (o *DelegatorDelegationsOKBodyDelegationResponsesItems0) contextValidateDelegation(ctx context.Context, formats strfmt.Registry) error {

	if o.Delegation != nil {
		if err := o.Delegation.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("delegation")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (o *DelegatorDelegationsOKBodyDelegationResponsesItems0) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *DelegatorDelegationsOKBodyDelegationResponsesItems0) UnmarshalBinary(b []byte) error {
	var res DelegatorDelegationsOKBodyDelegationResponsesItems0
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*DelegatorDelegationsOKBodyDelegationResponsesItems0Balance Coin defines a token with a denomination and an amount.
//
// NOTE: The amount field is an Int which implements the custom method
// signatures required by gogoproto.
swagger:model DelegatorDelegationsOKBodyDelegationResponsesItems0Balance
*/
type DelegatorDelegationsOKBodyDelegationResponsesItems0Balance struct {

	// amount
	Amount string `json:"amount,omitempty"`

	// denom
	Denom string `json:"denom,omitempty"`
}

// Validate validates this delegator delegations o k body delegation responses items0 balance
func (o *DelegatorDelegationsOKBodyDelegationResponsesItems0Balance) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this delegator delegations o k body delegation responses items0 balance based on context it is used
func (o *DelegatorDelegationsOKBodyDelegationResponsesItems0Balance) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *DelegatorDelegationsOKBodyDelegationResponsesItems0Balance) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *DelegatorDelegationsOKBodyDelegationResponsesItems0Balance) UnmarshalBinary(b []byte) error {
	var res DelegatorDelegationsOKBodyDelegationResponsesItems0Balance
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*DelegatorDelegationsOKBodyDelegationResponsesItems0Delegation Delegation represents the bond with tokens held by an account. It is
// owned by one delegator, and is associated with the voting power of one
// validator.
swagger:model DelegatorDelegationsOKBodyDelegationResponsesItems0Delegation
*/
type DelegatorDelegationsOKBodyDelegationResponsesItems0Delegation struct {

	// delegator_address is the bech32-encoded address of the delegator.
	DelegatorAddress string `json:"delegator_address,omitempty"`

	// shares define the delegation shares received.
	Shares string `json:"shares,omitempty"`

	// validator_address is the bech32-encoded address of the validator.
	ValidatorAddress string `json:"validator_address,omitempty"`
}

// Validate validates this delegator delegations o k body delegation responses items0 delegation
func (o *DelegatorDelegationsOKBodyDelegationResponsesItems0Delegation) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this delegator delegations o k body delegation responses items0 delegation based on context it is used
func (o *DelegatorDelegationsOKBodyDelegationResponsesItems0Delegation) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *DelegatorDelegationsOKBodyDelegationResponsesItems0Delegation) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *DelegatorDelegationsOKBodyDelegationResponsesItems0Delegation) UnmarshalBinary(b []byte) error {
	var res DelegatorDelegationsOKBodyDelegationResponsesItems0Delegation
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*DelegatorDelegationsOKBodyPagination pagination defines the pagination in the response.
swagger:model DelegatorDelegationsOKBodyPagination
*/
type DelegatorDelegationsOKBodyPagination struct {

	// next_key is the key to be passed to PageRequest.key to
	// query the next page most efficiently
	// Format: byte
	NextKey strfmt.Base64 `json:"next_key,omitempty"`

	// total is total number of results available if PageRequest.count_total
	// was set, its value is undefined otherwise
	Total string `json:"total,omitempty"`
}

// Validate validates this delegator delegations o k body pagination
func (o *DelegatorDelegationsOKBodyPagination) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this delegator delegations o k body pagination based on context it is used
func (o *DelegatorDelegationsOKBodyPagination) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *DelegatorDelegationsOKBodyPagination) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *DelegatorDelegationsOKBodyPagination) UnmarshalBinary(b []byte) error {
	var res DelegatorDelegationsOKBodyPagination
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
