// Code generated by go-swagger; DO NOT EDIT.

package query

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// New creates a new query API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) ClientService {
	return &Client{transport: transport, formats: formats}
}

/*
Client for query API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

// ClientOption is the option for Client methods
type ClientOption func(*runtime.ClientOperation)

// ClientService is the interface for Client methods
type ClientService interface {
	DelegatorDelegations(params *DelegatorDelegationsParams, opts ...ClientOption) (*DelegatorDelegationsOK, error)

	OracleParams(params *OracleParamsParams, opts ...ClientOption) (*OracleParamsOK, error)

	SigningInfo(params *SigningInfoParams, opts ...ClientOption) (*SigningInfoOK, error)

	SlashingParams(params *SlashingParamsParams, opts ...ClientOption) (*SlashingParamsOK, error)

	SetTransport(transport runtime.ClientTransport)
}

/*
  DelegatorDelegations delegators delegations queries all delegations of a given delegator address
*/
func (a *Client) DelegatorDelegations(params *DelegatorDelegationsParams, opts ...ClientOption) (*DelegatorDelegationsOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewDelegatorDelegationsParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "DelegatorDelegations",
		Method:             "GET",
		PathPattern:        "/cosmos/staking/v1beta1/delegations/{delegator_addr}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &DelegatorDelegationsReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*DelegatorDelegationsOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	unexpectedSuccess := result.(*DelegatorDelegationsDefault)
	return nil, runtime.NewAPIError("unexpected success response: content available as default response in error", unexpectedSuccess, unexpectedSuccess.Code())
}

/*
  OracleParams params queries all parameters
*/
func (a *Client) OracleParams(params *OracleParamsParams, opts ...ClientOption) (*OracleParamsOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewOracleParamsParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "OracleParams",
		Method:             "GET",
		PathPattern:        "/terra/oracle/v1beta1/params",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &OracleParamsReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*OracleParamsOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	unexpectedSuccess := result.(*OracleParamsDefault)
	return nil, runtime.NewAPIError("unexpected success response: content available as default response in error", unexpectedSuccess, unexpectedSuccess.Code())
}

/*
  SigningInfo signings info queries the signing info of given cons address
*/
func (a *Client) SigningInfo(params *SigningInfoParams, opts ...ClientOption) (*SigningInfoOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewSigningInfoParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "SigningInfo",
		Method:             "GET",
		PathPattern:        "/cosmos/slashing/v1beta1/signing_infos/{cons_address}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &SigningInfoReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*SigningInfoOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	unexpectedSuccess := result.(*SigningInfoDefault)
	return nil, runtime.NewAPIError("unexpected success response: content available as default response in error", unexpectedSuccess, unexpectedSuccess.Code())
}

/*
  SlashingParams params queries the parameters of slashing module
*/
func (a *Client) SlashingParams(params *SlashingParamsParams, opts ...ClientOption) (*SlashingParamsOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewSlashingParamsParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "SlashingParams",
		Method:             "GET",
		PathPattern:        "/cosmos/slashing/v1beta1/params",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &SlashingParamsReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*SlashingParamsOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	unexpectedSuccess := result.(*SlashingParamsDefault)
	return nil, runtime.NewAPIError("unexpected success response: content available as default response in error", unexpectedSuccess, unexpectedSuccess.Code())
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
