// Code generated by go-swagger; DO NOT EDIT.

package query

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewSigningInfoParams creates a new SigningInfoParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewSigningInfoParams() *SigningInfoParams {
	return &SigningInfoParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewSigningInfoParamsWithTimeout creates a new SigningInfoParams object
// with the ability to set a timeout on a request.
func NewSigningInfoParamsWithTimeout(timeout time.Duration) *SigningInfoParams {
	return &SigningInfoParams{
		timeout: timeout,
	}
}

// NewSigningInfoParamsWithContext creates a new SigningInfoParams object
// with the ability to set a context for a request.
func NewSigningInfoParamsWithContext(ctx context.Context) *SigningInfoParams {
	return &SigningInfoParams{
		Context: ctx,
	}
}

// NewSigningInfoParamsWithHTTPClient creates a new SigningInfoParams object
// with the ability to set a custom HTTPClient for a request.
func NewSigningInfoParamsWithHTTPClient(client *http.Client) *SigningInfoParams {
	return &SigningInfoParams{
		HTTPClient: client,
	}
}

/* SigningInfoParams contains all the parameters to send to the API endpoint
   for the signing info operation.

   Typically these are written to a http.Request.
*/
type SigningInfoParams struct {

	/* ConsAddress.

	   cons_address is the address to query signing info of
	*/
	ConsAddress string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the signing info params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *SigningInfoParams) WithDefaults() *SigningInfoParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the signing info params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *SigningInfoParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the signing info params
func (o *SigningInfoParams) WithTimeout(timeout time.Duration) *SigningInfoParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the signing info params
func (o *SigningInfoParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the signing info params
func (o *SigningInfoParams) WithContext(ctx context.Context) *SigningInfoParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the signing info params
func (o *SigningInfoParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the signing info params
func (o *SigningInfoParams) WithHTTPClient(client *http.Client) *SigningInfoParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the signing info params
func (o *SigningInfoParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithConsAddress adds the consAddress to the signing info params
func (o *SigningInfoParams) WithConsAddress(consAddress string) *SigningInfoParams {
	o.SetConsAddress(consAddress)
	return o
}

// SetConsAddress adds the consAddress to the signing info params
func (o *SigningInfoParams) SetConsAddress(consAddress string) {
	o.ConsAddress = consAddress
}

// WriteToRequest writes these params to a swagger request
func (o *SigningInfoParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param cons_address
	if err := r.SetPathParam("cons_address", o.ConsAddress); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
