// Code generated by go-swagger; DO NOT EDIT.

package query

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewSlashingParamsParams creates a new SlashingParamsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewSlashingParamsParams() *SlashingParamsParams {
	return &SlashingParamsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewSlashingParamsParamsWithTimeout creates a new SlashingParamsParams object
// with the ability to set a timeout on a request.
func NewSlashingParamsParamsWithTimeout(timeout time.Duration) *SlashingParamsParams {
	return &SlashingParamsParams{
		timeout: timeout,
	}
}

// NewSlashingParamsParamsWithContext creates a new SlashingParamsParams object
// with the ability to set a context for a request.
func NewSlashingParamsParamsWithContext(ctx context.Context) *SlashingParamsParams {
	return &SlashingParamsParams{
		Context: ctx,
	}
}

// NewSlashingParamsParamsWithHTTPClient creates a new SlashingParamsParams object
// with the ability to set a custom HTTPClient for a request.
func NewSlashingParamsParamsWithHTTPClient(client *http.Client) *SlashingParamsParams {
	return &SlashingParamsParams{
		HTTPClient: client,
	}
}

/* SlashingParamsParams contains all the parameters to send to the API endpoint
   for the slashing params operation.

   Typically these are written to a http.Request.
*/
type SlashingParamsParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the slashing params params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *SlashingParamsParams) WithDefaults() *SlashingParamsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the slashing params params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *SlashingParamsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the slashing params params
func (o *SlashingParamsParams) WithTimeout(timeout time.Duration) *SlashingParamsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the slashing params params
func (o *SlashingParamsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the slashing params params
func (o *SlashingParamsParams) WithContext(ctx context.Context) *SlashingParamsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the slashing params params
func (o *SlashingParamsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the slashing params params
func (o *SlashingParamsParams) WithHTTPClient(client *http.Client) *SlashingParamsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the slashing params params
func (o *SlashingParamsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *SlashingParamsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
